### ISSUE TITLE
File "C:/Users/uiss-/PycharmProjects/SamOS/Plugins/database/chat_database.py", line 30

### ISSUE THREAD

**Issue by Gamelounch** [Gamelounch/SamOS-Deep-Learnin-AI#2]
File "C:/Users/uiss-/PycharmProjects/SamOS/Plugins/database/chat_database.py", line 30
    except Exception as e:

Something is Wrong with that. I need to Fix it Later on

**Comment by Gamelounch** [comment]
I Changed the line but now i get 2 Error Codes.

C:\Users\uiss-\PycharmProjects\SamOS\venv\Scripts\python.exe C:/Users/uiss-/Documents/GitHub/Classic/Plugins/database/chat_database.py
Traceback (most recent call last):
  File "C:/Users/uiss-/Documents/GitHub/Classic/Plugins/database/chat_database.py", line 38, in <module>
    create_table()
  File "C:/Users/uiss-/Documents/GitHub/Classic/Plugins/database/chat_database.py", line 17, in create_table
    comment TEXT, subreddit TEXT, unix INT, score INT )""")
sqlite3.OperationalError: near "EXIST": syntax error

**Comment by Gamelounch** [comment]
Done
